name: Currency UI Deployment
run-name: Currency UI {{ github.run_id }}
on:
  push:
    branches:
      - master

jobs:
  build_web_app:
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - run: mkdir artifact
      - run: ls

      - run: echo Hello World! > artifact/test.txt
      - uses: actions/upload-artifact@master
        with:
          name: my-artifact
          path: artifact

  download_web_app:
    name: Download Web App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@master
        with:
          name: my-artifact
          path: path/to/artifact
      - run: cat path/to/artifact/test.txt
